/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmyshowui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.ScrollPaneLayout;
import javax.swing.SpringLayout;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicOptionPaneUI;

/**
 *
 * @author Sanjib
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private String url = "jdbc:sqlserver://HP-PC;instanceName=SQLEXPRESS;DatabaseName=BookMyShow;integratedSecurity=true";
    private Connection myCon;
    private Statement stmt;
    
    public Home() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        textMovieName = new javax.swing.JTextField();
        searchMovie = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        LoggedInUserName = new javax.swing.JLabel();
        LogOff = new javax.swing.JButton();
        searchedMovieResult = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("BookMyShow");

        jButton1.setText("Booking History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select City");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kolkata", "Mumbai", "Delhi", "Pune" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Movie");

        textMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMovieNameActionPerformed(evt);
            }
        });

        searchMovie.setText("Search");
        searchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMovieActionPerformed(evt);
            }
        });

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        LoggedInUserName.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        LoggedInUserName.setForeground(new java.awt.Color(204, 0, 255));

        LogOff.setText("LogOff");
        LogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOffActionPerformed(evt);
            }
        });

        searchedMovieResult.setBorder(null);
        searchedMovieResult.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchedMovieResult)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(LoggedInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LogOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(26, 26, 26)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(searchMovie)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(LoggedInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LogOff)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMovie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchedMovieResult, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMovieNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BookingHistory bk = new BookingHistory();
        this.dispose();
        bk.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void searchMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMovieActionPerformed
        // TODO add your handling code here:
        String searchText = textMovieName.getText();
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            myCon = DriverManager.getConnection(url);
            stmt = myCon.createStatement();
            String getSearchData = "select * from Movie" +
                                    "  join ScreenMovie" +
                                    "  on Movie.MovieId = ScreenMovie.MovieId" +
                                    "  join Screen" +
                                    "  on ScreenMovie.ScreenId = Screen.ScreenId" +
                                    "  join Theatre" +
                                    "  on Screen.TheatreId = Theatre.TheatreId" +
                                    "  where Movie.MovieName LIKE '%"+searchText+"%' and Theatre.City = '"+String.valueOf(jComboBox1.getSelectedItem())+"'";
            
            ResultSet rst = stmt.executeQuery(getSearchData);
            searchedMovieResult.removeAll();
            searchedMovieResult.repaint();
            final JFrame mainFrame = this;
            int height = 50;
            int width = 856;
            int count = 0;
            final JPanel jp = new JPanel(new GridLayout(0, 3, 0, 5));
            
            JLabel jlbl1 = new JLabel();
            jlbl1.setText("<html><div style='font-size: 16px; color: #428bca;'>Movie Name</div></html>");
            //jlbl1.setForeground(Color.BLUE);
            jp.add(jlbl1);
            
            JLabel jlbl2 = new JLabel();
            jlbl2.setText("<html><div style='font-size: 16px; color: #428bca;'>Actor</div></html>");
            jp.add(jlbl2);
            
            JLabel jlbl3 = new JLabel();
            jlbl3.setText("<html><div style='font-size: 16px; color: #428bca;'> </div></html>");
            jp.add(jlbl3);
            
            while(rst.next())
            {
                System.out.println(rst.getString("MovieName"));
                //FlowLayout fl = new FlowLayout(FlowLayout.LEADING);
                //jp.setLayout(new BoxLayout(jp, BoxLayout.LINE_AXIS));
                //jp.setLayout(new GridLayout());
                //jp.setBackground(Color.white);
                //jp.setLayout(new BorderLayout());
                //jp.setLayout(new FlowLayout());
                if(count == 0)
                {
                    jp.setSize(width, height);
                    count++;
                }
                else
                {
                    height += 50;
                    jp.setSize(width, height);
                }
                
                JLabel j1 = new JLabel();
                //j1.setSize(300, 45);
                j1.setText(rst.getString("MovieName"));
                jp.add(j1);
                
                JLabel j2 = new JLabel();
                //j2.setSize(300, 45);
                j2.setText(rst.getString("Starring"));
                jp.add(j2);
                
                JButton jb = new JButton("Show Theatres");
                //jb.setPreferredSize(new Dimension(40, 40));
                //jb.setBounds(20,30,50,30);
                //jb.setSize(100, 45);
                jb.setActionCommand(rst.getString("MovieId"));
                jb.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String getSearchData = "select * from ScreenMovie" +
                                                "  join Screen" +
                                                "  on ScreenMovie.ScreenId = Screen.ScreenId" +
                                                "  join Theatre" +
                                                "  on Screen.TheatreId = Theatre.TheatreId" +
                                                "  where ScreenMovie.MovieId = '"+ ((JButton) e.getSource()).getActionCommand() +"' and Theatre.City = '"+String.valueOf(jComboBox1.getSelectedItem())+"'";
                        
                        try {
                            ResultSet rst = stmt.executeQuery(getSearchData);
                            jp.removeAll();
                            jp.repaint();
                            jp.setLayout(new GridBagLayout());
                            GridBagConstraints c = new GridBagConstraints();
                            c.fill = GridBagConstraints.HORIZONTAL;
                            while(rst.next())
                            {
                                System.out.println(rst.getString("TheatreName"));
                                JLabel lbl = new JLabel(rst.getString("TheatreName"));
                                c.weightx = 0.1;
                                //c.gridx = 1;
                                c.ipady = 20;
                                c.gridy = 0;
                                jp.add(lbl, c);
                                
                                JLabel lb2 = new JLabel(rst.getString("Date"));
                                jp.add(lb2, c);
                                
                                JLabel lb3 = new JLabel();
                                
                                switch(rst.getString("ShowNumber"))
                                {
                                    case "1": 
                                        lb3.setText("9 AM - 12 PM");
                                        break;
                                    case "2":
                                        lb3.setText("12 PM - 3 PM");
                                        break;
                                    case "3":
                                        lb3.setText("3 PM - 6 PM");
                                        break;
                                    case "4":
                                        lb3.setText("6 PM - 9 PM");
                                        break;
                                }
                                
                                jp.add(lb3, c);
                                
                                JButton btnBook = new JButton("Book Now");
                                //c.weightx = 0.1;
                                //c.gridx = 1;
                                //c.anchor = GridBagConstraints.CENTER;
                                c.ipady = 20;
                                c.gridy = 0;
                                
                                btnBook.setActionCommand(rst.getString("ScreenId"));
                                btnBook.addActionListener(new ActionListener() {
                                    @Override
                                    public void actionPerformed(ActionEvent e) {
                                        BookMyShow bms = new BookMyShow();
                                        BookSeat bs;
                                        
                                        bms.setSereenId(((JButton) e.getSource()).getActionCommand());
                                        mainFrame.dispose();
                                        try {
                                            BookSeat.screenId = bms.getSereenId();
                                            bs = new BookSeat();
                                            bs.setVisible(true);
                                        } catch (ClassNotFoundException ex) {
                                            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                        
                                    }
                                    
                                });
                                
                                jp.add(btnBook, c);
                            }
                            jp.validate();
                        } catch (SQLException ex) {
                            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                jp.add(jb);
                
            }
            searchedMovieResult.add(jp);
            mainFrame.add(searchedMovieResult);
            mainFrame.setLayout(null);
            //this.setVisible(true);
            mainFrame.validate();
            
        }
        catch(SQLException | ClassNotFoundException se)
        {
            se.printStackTrace();
        }
    }//GEN-LAST:event_searchMovieActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login lgn = new Login();
        this.dispose();
        lgn.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Register reg = new Register();
        this.dispose();
        reg.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
            
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton LogOff;
    public javax.swing.JLabel LoggedInUserName;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchMovie;
    private javax.swing.JScrollPane searchedMovieResult;
    public javax.swing.JTextField textMovieName;
    // End of variables declaration//GEN-END:variables

    
}

